### ISSUE TITLE
Rest chat message for newer 11.2.0+ sheet

### ISSUE THREAD

**Issue by ChaosMonkeyBoy** [symposion/roll20-shaped-scripts#481] opened 2017-04-16 17:26 UTC
Create a chat message for newer sheet rests as per:
[11.2.0 sheet update](https://app.roll20.net/forum/post/4450188/5e-shaped-version-8-plus/?pageforid=4839001#post-4839001)

**Comment by symposion** [comment] 2017-04-16 19:27
This functionality was already been implemented a while ago. There was a bug ( #482 ) that caused an error sometimes which I have now fixed. I suspect that the reason you raised this issue is that the sheet does not send any output if the rest makes no changes. If you think this behaviour is incorrect you should raise an issue against the sheet.

**Comment by symposion** [comment] 2017-04-16 19:28
NB the fix for 482 has not been released yet - but will be later this evening.

**Closed by symposion** 2017-04-16 19:27 UTC
Labels: invalid

**Comment by ChaosMonkeyBoy** [comment] 2017-04-16 19:36
I get no output on 11.5.0 sheet at all except error message to gm.

**Comment by symposion** [comment] 2017-04-16 19:46
Yes, that's #482 . I'd assumed that you weren't getting any output at all since you didn't mention anything about an error in the issue description. Either way, this will be fixed in the next release which should go out later this evening, assuming Travis CI deals with their backlog soon enough to actually run my release build :-/

**Comment by ChaosMonkeyBoy** [comment] 2017-04-16 19:49
Thanks for all of your hard work! Just want to make sure to point out anything out of order that I see.

**Comment by symposion** [comment] 2017-04-16 19:53
Yep, please do - that's really helpful! For best results for both of us, try to include as much detail about the problem as possible in your tickets - reproduction steps, expected behaviour and actual behaviour; that way there's no room for misunderstanding. Cheers!

**Comment by ChaosMonkeyBoy** [comment] 2017-04-16 23:31
Working now, but no name shows up in template. Message in API output console:
"ERROR: Did not specify an attribute name when referencing attribute using @{character_name}"
"ERROR: Did not specify an attribute name when referencing attribute using @{show_character_name}"
