### ISSUE TITLE
"Apply to all new chars?" setting not working

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#400] opened 2017-03-19 17:53 UTC
Using latest sheet 11.0.0 and companion 8.0.0 (but I had same issue on the release before this, just re-tested).

Adding NPC's through the roll20 compendium (from MM if that matters) and then dragging onto a page does not set the shaped defaults for me.

Using "!shaped-apply-defaults" works, but to fix the token numbering I need to re-drag the character (I think that is working as expected, same for tokenmod + tokennamenumber combo).

Current activated scripts other than companion: TokenNamenumber Vector Math MatrixMath Path Math

**Comment by symposion** [comment] 2017-03-19 18:11
Hi,

Can you explain exactly what steps you are following and how the results differ from what you expect? I'm not 100% clear what you're doing since there are a number of different ways to use the Compendium

**Comment by liquidox** [comment] 2017-03-19 18:29
I made a 800 KB video showing the behavior:
https://hel.gefjun.net/share-download/9e707975-72e0-4336-a385-240f5d7707ae

**Comment by symposion** [comment] 2017-03-19 18:43
Ah, I see. It's applying the defaults to the character but not the token. I'm struggling to test this because this only applies to Compendium content that has pre-configured token, and this is only paid content. I don't have enough money to be dropping $50 on modules/digital copies of things I already own, so I've not been able to see how this work. I've asked Roll20 on numerous occasions whether some sort of test content could be made available so developers like me and Kryx can test this stuff, but I've had no response, sadly. I'll see what I can do but it's a huge PITA without being able to test it myself.

**Comment by liquidox** [comment] 2017-03-20 03:38
Ye you're not the first to mention this. It's crazy, roll20 is the first company I've run into that doesn't roll out the red carpet for volunteers improving their product greatly.

Only having recently joined roll20, the general attitude of their Developers and the responses on the forum are disappointing, and not in line with my expectations.

**Comment by liquidox** [comment] 2017-03-20 09:41
I now tested this with a brand new PC character sheet and am seeing similar behavior:

- Token actions not being set.
- Token bars wrong

For the token bar options I am using the following settings:
http://imgur.com/aIpFImA

The result on the token was:
bar1 - no values, no link
bar2 - current value, no link
bar 3- current value, no link

So there's some relation to the settings, but it's not correct. After !shaped-apply-defaults all looks fixed.

**Comment by symposion** [comment] 2017-03-20 12:41
Ok, so I've looked into this now. This is essentially working as expected, but it may be that we want to tweak the behaviour somewhat. Let me explain:

When you create a new character through the journal, you create an empty character object. It contains no actions and has no association with any token. At this point, the script detects the new character has been created (and this is the only point at which it gets a chance to take action; I can't, for example, detect when you close the character sheet after you finish editing it) and it applies all of the settings that are listed under new character settings, with the exception of the token actions. 

At this stage there is no token for the character, so the script cannot configure the token bars (these are settings on the token, not the character). In theory I might be able to watch for changes to the "represents character" attribute of a token and apply token defaults at that point, but I think that has the potential for unexpected consequences, since it will apply whenever people change the character for a token, not just for new characters; this has the potential to overwrite things that people have already set up and I don't think it's worth it just to avoid having to click a macro button to run !shaped-apply-defaults.

The token actions situation is a bit more complicated. The problem is that token actions are created based on what is contained in the character sheet. You can configure your default token actions to include pretty much every possible option - lair actions, legendaries, regional effects, etc, and it will only create a button for each one if the character has those items. But this can only work once the character sheet is populated. As I explained above, the only hook I have is immediately after the empty character is created, so at that point most of the token action creators aren't going to make anything - you'll probably just end up with ability checks, saves and rests. I'm not really interested in changing the behaviour of the token action maker to ignore what's present in the character sheet because this is extremely useful for people doing lots of different tokens with different capabilities; and given that you're going to have to run !shaped-apply-defaults to deal with the token bars anyway, it's not going to make much difference!

For PCs I don't see this as an issue. Having to run !shaped-apply-defaults for the handful of PC sheets/tokens in a campaign is really not an issue.

MM drag **is** an issue, and I'd like to fix that but at the moment (1) I have no way of testing it and (2) based on my limited understanding of how it works it may be very difficult, because I don't get any notification when the character is completely configured. Fixing this would entail Kryx rewriting a big chunk of how his sheet works and he's understandably unenthusiastic about doing that right now. It's possible that I might be able to sort out the token bars for MM drag without him doing that, but again, I can't test so I'm a bit stuck.

One alternative that you might consider is using the **!shaped-import-monster** command, for which all of this functionality works as expected. Obviously you have to drag/find a token first, but otherwise for me this is generally a superior solution to the other ways of importing a monster.

**Comment by liquidox** [comment] 2017-03-21 02:30
Thanks for your extensive analysis. I agree there's not really much of an issue for PC's, the fix is fast and reliable.

Regarding MM drag, it would be nice to have it work, but from my understanding the %%numbered%% system will always need re-drag, so while it would be nice to have, I would not consider it a major need.

**Comment by symposion** [comment] 2017-03-26 10:18
I'm closing this because I've now opened #429 and #430 to cover the generic problem behind this.

**Closed by symposion** 2017-03-26 10:18 UTC
