### ISSUE TITLE
!shaped-apply-defaults overwrites existing token values with blank values

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#432] opened 2017-03-26 19:43 UTC
I purchased Yawning Portal and have been trying to convert it cleanly to the Shaped Sheet.  The maps include all of the tokens with HP set to bar 1 and AC to bar 2.

When selecting a token and running !shaped-apply-defaults it does apply the proper configuration (hooray!), however it wipes out the existing token values, which means that any token where this command is run needs to be replaced.

**Comment by symposion** [comment] 2017-03-29 06:14
This appears to be related to: https://bitbucket.org/mlenser/5eshaped/issues/404/bar-linking-not-working-correctly-on I'm still unsure how much of this is sheet vs script - I suspect that the two are arguing somewhere and this is causing the problem.

At least part of the issue is a case sensitivity thing - the OGL uses lower case hp and ac whereas shaped uses upper. I have put in a fix for this for the next version of the script so the bar attribute matching is now case insensitive (the sheet workers are all case insensitive)

**Comment by beeke01** [comment] 2017-04-02 23:10
This seems to be resolved with 8.2.1 and/or the sheet 11.3.1, so this can be closed!

**Comment by symposion** [comment] 2017-04-03 09:49
It's improved, but I suspect that there are cases where it might still happen. I'm currently working on a total rewrite of this stuff based on some new code that Kryx added to the sheet that lets me hook into when all sheetworker processing is completed. This allows me to remove a lot of kludge that I had with the token/character defaults.

**Closed** 2017-04-09 17:56 UTC
Labels: fixedInDev
